# -*- coding: utf-8 -*-
"""Bank_Marketing_Inspection_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHQnIedWP1vSSER158w7a9LnHtmSVC_0

# Bank Marketing Data Analysis
This notebook presents an analysis of the `bankmarketing.csv` dataset, which includes data related to a bank's marketing campaigns. The main goal is to understand customer behavior and predict whether a client will subscribe to a term deposit.
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('bankmarketing.csv')

# Display the first few rows
df.head()

print(df.info())
print("\nMissing values per column:")
print(df.isnull().sum())

df.describe()

import seaborn as sns
import matplotlib.pyplot as plt
sns.countplot(x='y', data=df)
plt.title('Distribution of Subscriptions (y)')
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix')
plt.show()

"""
## Conclusion

In this analysis, we explored the structure and composition of the bank marketing dataset. Key takeaways include:

- The dataset includes customer demographics and contact details, which can be useful for segmentation.
- A majority of customers do not subscribe to term deposits, indicating an imbalanced dataset.
- Further preprocessing, feature engineering, and modeling would be the next steps for predictive analysis.

This initial inspection sets the foundation for a deeper analysis or machine learning workflow to improve marketing effectiveness.
"""